### ISSUE TITLE
Can't create task

### ISSUE THREAD

**Issue by SiDronee** [jbinder/doforme-bot#1]
after the /do TEST, the bot repeats saying:  add bot to group.
The bot is added to a group.

**Comment by jbinder** [comment]
Thanks for the feedback! In order to allow the bot to pick up the users in the group, it currently is required that every person in the group writes a message to the group. This also makes the bot aware of the group and should resolve your issue. I will add this info to the docs.

**Comment by jbinder** [comment]
I updated the README to clarify the behavior.
